application: aloboxdeneme
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico, index.html,signup.html,activasyon.html,dashboard.html,login.html, cloudstorage/.*
  upload: favicon\.ico, index\.html,signup\.html,activasyon\.html,dashboard\.html,login\.html
  

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
  
